<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxncvjh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxncvjh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTxncvjh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTxncvjh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTxncvjh\appProdProjectContainer([
    'container.build_hash' => 'Txncvjh',
    'container.build_id' => '28ccf320',
    'container.build_time' => 1644393117,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxncvjh');
