<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR6h70jm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR6h70jm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerR6h70jm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerR6h70jm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerR6h70jm\appProdProjectContainer([
    'container.build_hash' => 'R6h70jm',
    'container.build_id' => 'aa2d81b1',
    'container.build_time' => 1644805119,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR6h70jm');
