<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFspixfy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFspixfy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFspixfy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFspixfy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFspixfy\appProdProjectContainer([
    'container.build_hash' => 'Fspixfy',
    'container.build_id' => 'b9d18dba',
    'container.build_time' => 1645172737,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFspixfy');
