{**
 * NOTICE OF LICENSE
 *
 * This source file is subject to a commercial license from Common-Services Co., Ltd.
 * Use, copy, modification or distribution of this source file without written
 * license agreement from Common-Services Co., Ltd. is strictly forbidden.
 * In order to obtain a license, please contact us: contact@common-services.com
 * ...........................................................................
 * INFORMATION SUR LA LICENCE D'UTILISATION
 *
 * L'utilisation de ce fichier source est soumise a une licence commerciale
 * concedee par la societe Common-Services Co., Ltd.
 * Toute utilisation, reproduction, modification ou distribution du present
 * fichier source sans contrat de licence ecrit de la part de la Common-Services Co. Ltd. est
 * expressement interdite.
 * Pour obtenir une licence, veuillez contacter Common-Services Co., Ltd. a l'adresse: contact@common-services.com
 *
 * @package   CDiscount
 * @author    Olivier B.
 * @copyright Copyright (c) Since 2011 Common Services Co Ltd - 90/25 Sukhumvit 81 - 10260 Bangkok - Thailand
 * @license   Commercial license
 * Support by mail:  support.cdiscount@common-services.com
*}

<div>
    {if (isset($context_key))}
        <input type="hidden" name="context_key" value="{$context_key|escape:'htmlall':'UTF-8'}"/>
    {/if}
    <input type="hidden" id="serror"
           value="{l s='A server-side error has occured. Please contact your server administrator, hostmaster or webmaster' mod='cdiscount'}"/>
    <input type="hidden" id="sdebug"
           value="{l s='You should click on this link to submit again in debug mode' mod='cdiscount'}"/>
    <img style="float:right;" src="{$images|escape:'htmlall':'UTF-8'}clemarche_1.png"
         alt="{l s='Cdiscount Marketplace' mod='cdiscount'}'.$this->l('Cdiscount Marketplace').'"/>
    <img style="float:left;" src="{$images|escape:'htmlall':'UTF-8'}cdiscount.png"
         alt="{l s='CDiscount' mod='cdiscount'}'.$this->l('CDiscount').'"/>
</div>
<div style="clear:both;padding-bottom:20px;"></div>

<p style="color:brown;font-weight:bold">
    {l s='For any support, and unconditionnaly, you should provide the file generated by the module and the integration report, you can download it in your CDiscount\'s backend.' mod='cdiscount'}
</p>
<br/>